# coding: utf-8
import re

RE_SIMPLE_STR = r'(?P<price>[\d\.\,ю]+)(?:\s+)?(?P<currency>USD|BYR|BYN|RUB|UAH|EUR|PLN)?(?:\s+)?(?P<note>[\w].*?)(?:  |$|;)'
RE_SIMPLE = re.compile(RE_SIMPLE_STR, re.U | re.I)

RE_REMOVE_PURCHASE_STR = r'remove|rm|del(?:\s+)?(?P<purchase_id>[\d]+)'
RE_REMOVE_PURCHASE = re.compile(RE_REMOVE_PURCHASE_STR, re.U | re.I)

RE_INT_STR = r'(?P<integer>[\d]+)'
RE_INT = re.compile(RE_INT_STR, re.U | re.I)

OLD_BELARUSSIAN_RUBLE_CODE = 'BYR'
NEW_BELARUSSIAN_RUBLE_CODE = 'BYN'

UI_CANCEL_BUTTON = 'отмена ввода'

EXPENSE_COMMUNAL = 'коммуналка'
EXPENSE_PRODUCT_SHOP = 'магазин'
EXPENSE_FEE = 'сборы'
EXPENSE_DOMESTIC = 'бытовые'
EXPENSE_HEALTH = 'здоровье'
EXPENSE_TRANSPORT = 'транспорт'
EXPENSE_BEAUTY = 'красота'
EXPENSE_NTERTAINMENT = 'развлечения'
EXPENSE_BUY = 'покупки'
EXPENSE_CHILD = 'ребенок'
EXPENSE_HOME_BUILDING = 'стройка'
EXPENSE_ANOTHER = 'иное'

EXPENSES_NAMES = (EXPENSE_COMMUNAL, EXPENSE_PRODUCT_SHOP, EXPENSE_FEE,
                  EXPENSE_DOMESTIC, EXPENSE_HEALTH, EXPENSE_TRANSPORT,
                  EXPENSE_BEAUTY, EXPENSE_NTERTAINMENT, EXPENSE_BUY,
                  EXPENSE_CHILD, EXPENSE_HOME_BUILDING, EXPENSE_ANOTHER)

EXPENSES = (
    ('1', EXPENSE_COMMUNAL),
    ('2', EXPENSE_PRODUCT_SHOP),
    ('3', EXPENSE_FEE),
    ('4', EXPENSE_DOMESTIC),
    ('5', EXPENSE_HEALTH),
    ('6', EXPENSE_TRANSPORT),
    ('7', EXPENSE_BEAUTY),
    ('8', EXPENSE_NTERTAINMENT),
    ('9', EXPENSE_BUY),
    ('10', EXPENSE_CHILD),
    ('11', EXPENSE_HOME_BUILDING),
    ('12', EXPENSE_ANOTHER),
)

UI_CANCEL_INDEX = str(len(EXPENSES) + 1)

REPLY_EXPENSES = EXPENSES + ((UI_CANCEL_INDEX, UI_CANCEL_BUTTON),)

NOTES_ALWAYS_NEED_MENU = ('BLR MOBILE BANK',)
NOTES_NEVER_NEED_MENU = (
    ('NLD UBER', EXPENSE_TRANSPORT),
)

SIMPLE_TYPE = 's'
DELIMETER = '|'
REMEMBERED_EXPENSE_DUBLICATES_COUNT = 2
